create extension if not exists pgcrypto;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  normalized_name text not null unique,
  brand text,
  product_name text not null,
  category text,
  slug text unique,
  aliases text[] not null default '{}',
  status text not null default 'provisional' check (status in ('provisional', 'verified', 'archived')),
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quick_scans (
  id uuid primary key default gen_random_uuid(),
  product_id uuid references public.products(id) on delete set null,
  query text not null,
  normalized_query text not null,
  market text not null default 'United States',
  status text not null default 'ready' check (status in ('processing', 'ready', 'failed', 'archived')),
  result jsonb not null default '{}'::jsonb,
  source_count integer not null default 0,
  confidence text not null default 'low' check (confidence in ('high', 'medium', 'low')),
  model text,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (normalized_query, market)
);

create table if not exists public.search_events (
  id bigint generated by default as identity primary key,
  query text not null,
  normalized_query text not null,
  market text not null default 'United States',
  result_type text not null check (result_type in ('verified_page', 'cached_scan', 'live_scan', 'rate_limited', 'failed')),
  ip_hash text,
  created_at timestamptz not null default now()
);

create index if not exists quick_scans_expiry_idx on public.quick_scans (expires_at desc);
create index if not exists quick_scans_product_idx on public.quick_scans (product_id);
create index if not exists search_events_query_idx on public.search_events (normalized_query, created_at desc);
create index if not exists search_events_ip_idx on public.search_events (ip_hash, created_at desc);

alter table public.products enable row level security;
alter table public.quick_scans enable row level security;
alter table public.search_events enable row level security;

revoke all on public.products from anon, authenticated;
revoke all on public.quick_scans from anon, authenticated;
revoke all on public.search_events from anon, authenticated;

grant all on public.products to service_role;
grant all on public.quick_scans to service_role;
grant all on public.search_events to service_role;
grant usage, select on sequence public.search_events_id_seq to service_role;

comment on table public.quick_scans is 'Provisional, non-indexed AI-assisted research cached for repeated searches.';
comment on table public.search_events is 'Demand signals and anonymous rate-limit records; stores only a salted IP hash.';
